### ISSUE TITLE
fix build on netlify

### ISSUE THREAD

**Issue by bladicito** [ost-cas-fee-adv-23-24/nextjs-app-football-fanatics#33]
Netlify dashboard needs to be updated with all needed env variables. 
It seems like the amplify prebuilds cannot be used while we are using netilify.

**Comment by lehmi11** [comment]
Preview build are deployed to dynamic urls/domains. This results in untrusted hosts errors. After merging the PRs to the master branch, the deployment url is https://elbmum.netlify.app/ which is trusted by our config.
