### ISSUE TITLE
create presentation

### ISSUE THREAD

**Issue by lehmi11** [ost-cas-fee-adv-23-24/nextjs-app-football-fanatics#67]
- [ ] Demo Mumble
- [ ] Architekturentscheide:
   - [ ] Middleware.ts
   - [ ] Providers / Context
   - [ ] revalidationPath
   - [ ] detailed Post page (full serverside rendered)
   - [ ] auth.ts von Testing / fixed
- [ ] Extras / Highlights
   - [ ] Feed (infinite scrolling)
   - [ ] env zod validation
   - [ ] Modal Provider
   - [ ] mentions of users (dropdown)

**Comment by lehmi11** [comment]
![image](https://github.com/ost-cas-fee-adv-23-24/nextjs-app-football-fanatics/assets/43446100/65c187b0-0fc4-408e-8925-018416eaa242)

**Comment by lehmi11** [comment]
![image](https://github.com/ost-cas-fee-adv-23-24/nextjs-app-football-fanatics/assets/43446100/fbdb203f-292f-4bfd-a24e-a50b85aa51d2)

**Comment by bladicito** [comment]
done!
[Mumble App Football Fanatics.pptx](https://github.com/ost-cas-fee-adv-23-24/nextjs-app-football-fanatics/files/15313210/Mumble.App.Football.Fanatics.pptx)
